// app/utils/players.ts

export interface Player {
  name: string;
  country: string;
  club: string;
  league: string;
}

const GROUP_A: Player[] = [
  // מקסיקו
  { name: "אדסון אלברס", country: "מקסיקו", club: "ווסטהאם יונייטד", league: "Premier League" },
  { name: "סנטיאגו חימנס", country: "מקסיקו", club: "פיינורד", league: "Eredivisie" },
  { name: "הירווינג לוסאנו", country: "מקסיקו", club: "פ.ס.וו איינדהובן", league: "Eredivisie" },
  { name: "ססאר מונטס", country: "מקסיקו", club: "לוקומוטיב מוסקבה", league: "Russian Premier League" },
  { name: "יוהאן ואסקיס", country: "מקסיקו", club: "גנואה", league: "Serie A" },
  { name: "לואיס רומו", country: "מקסיקו", club: "קרוס אסול", league: "Liga MX" },
  { name: "חוליאן קיניונס", country: "מקסיקו", club: "אל-קאדסיה", league: "Saudi Pro League" },
  { name: "לואיס צ'אבס", country: "מקסיקו", club: "דינמו מוסקבה", league: "Russian Premier League" },
  { name: "אורבלין פינדה", country: "מקסיקו", club: "א.א.ק אתונה", league: "Super League Greece" },
  { name: "חורחה סאנצ'ס", country: "מקסיקו", club: "קרוס אסול", league: "Liga MX" },
  { name: "לואיס מלאגון", country: "מקסיקו", club: "קלוב אמריקה", league: "Liga MX" },
  { name: "אוריאל אנטונה", country: "מקסיקו", club: "טיגרס", league: "Liga MX" },
  { name: "הנרי מרטין", country: "מקסיקו", club: "קלוב אמריקה", league: "Liga MX" },
  { name: "חסוס גאיארדו", country: "מקסיקו", club: "דפורטיבו טולוקה", league: "Liga MX" },
  { name: "רוברטו אלברדו", country: "מקסיקו", club: "גוודלחרה", league: "Liga MX" },
  // דרום אפריקה
  { name: "רונוון ויליאמס", country: "דרום אפריקה", club: "ממלודי סנדאונס", league: "South African Premier Division" },
  { name: "פרסי טאו", country: "דרום אפריקה", club: "אל אהלי", league: "Egyptian Premier League" },
  { name: "תמבה זוואנה", country: "דרום אפריקה", club: "ממלודי סנדאונס", league: "South African Premier Division" },
  { name: "טבוהו מוקואנה", country: "דרום אפריקה", club: "ממלודי סנדאונס", league: "South African Premier Division" },
  { name: "חוליסו מודאו", country: "דרום אפריקה", club: "ממלודי סנדאונס", league: "South African Premier Division" },
  { name: "סיאנדה קולו", country: "דרום אפריקה", club: "סופרספורט יונייטד", league: "South African Premier Division" },
  { name: "מייקלה מאיאמבלה", country: "דרום אפריקה", club: "אריס לימסול", league: "Cypriot First Division" },
  { name: "לייל פוסטר", country: "דרום אפריקה", club: "ברנלי", league: "Championship" },
  { name: "ספפלו סיטהולה", country: "דרום אפריקה", club: "טונדלה", league: "Liga Portugal 2" },
  { name: "מוטובי מבאלה", country: "דרום אפריקה", club: "ממלודי סנדאונס", league: "South African Premier Division" },
  { name: "אוברי מודיבה", country: "דרום אפריקה", club: "ממלודי סנדאונס", league: "South African Premier Division" },
  { name: "אוזווין אפוליס", country: "דרום אפריקה", club: "פולוקוואנה סיטי", league: "South African Premier Division" },
  { name: "גרנט קקאנה", country: "דרום אפריקה", club: "ממלודי סנדאונס", league: "South African Premier Division" },
  { name: "אווידנס מקגופה", country: "דרום אפריקה", club: "אורלנדו פיירטס", league: "South African Premier Division" },
  { name: "ויליוט משאמבה", country: "דרום אפריקה", club: "דאלאס", league: "MLS" },
  // קוריאה הדרומית
  { name: "סון יונג-מין", country: "קוריאה הדרומית", club: "טוטנהאם הוטספור", league: "Premier League" },
  { name: "קים מין-ג'אה", country: "קוריאה הדרומית", club: "באיירן מינכן", league: "Bundesliga" },
  { name: "לי קאנג-אין", country: "קוריאה הדרומית", club: "פריז סן ז'רמן", league: "Ligue 1" },
  { name: "הוואנג הי-צ'אן", country: "קוריאה הדרומית", club: "וולברהמפטון וונדררס", league: "Premier League" },
  { name: "הוואנג אין-בום", country: "קוריאה הדרומית", club: "פיינורד", league: "Eredivisie" },
  { name: "לי ג'ה-סונג", country: "קוריאה הדרומית", club: "מיינץ 05", league: "Bundesliga" },
  { name: "צ'ו גו-סונג", country: "קוריאה הדרומית", club: "מיטיולן", league: "Danish Superliga" },
  { name: "הונג היון-סוק", country: "קוריאה הדרומית", club: "מיינץ 05", league: "Bundesliga" },
  { name: "סול יאנג-וו", country: "קוריאה הדרומית", club: "הכוכב האדום בלגרד", league: "Serbian SuperLiga" },
  { name: "קים ג'ו-סונג", country: "קוריאה הדרומית", club: "פ.צ. סיאול", league: "K League 1" },
  { name: "קים סונג-גיו", country: "קוריאה הדרומית", club: "אל-שבאב", league: "Saudi Pro League" },
  { name: "פארק יונג-וו", country: "קוריאה הדרומית", club: "אל עין", league: "UAE Pro League" },
  { name: "ג'ונג וו-יונג", country: "קוריאה הדרומית", club: "אוניון ברלין", league: "Bundesliga" },
  { name: "או היון-גיו", country: "קוריאה הדרומית", club: "גנק", league: "Belgian Pro League" },
  { name: "ג'ו היון-וו", country: "קוריאה הדרומית", club: "אולסן יונדאי", league: "K League 1" },
  // צ'כיה
  { name: "תומאש סוצ'ק", country: "צ'כיה", club: "ווסטהאם יונייטד", league: "Premier League" },
  { name: "פטריק שיק", country: "צ'כיה", club: "באייר לברקוזן", league: "Bundesliga" },
  { name: "ולדימיר צופאל", country: "צ'כיה", club: "ווסטהאם יונייטד", league: "Premier League" },
  { name: "אנטונין בראק", country: "צ'כיה", club: "קסימפאשה", league: "Süper Lig" },
  { name: "תומאש הולש", country: "צ'כיה", club: "סלביה פראג", league: "Czech First League" },
  { name: "לדיסלאב קרייצ'י", country: "צ'כיה", club: "ז'ירונה", league: "La Liga" },
  { name: "לוקאש פרובוד", country: "צ'כיה", club: "סלביה פראג", league: "Czech First League" },
  { name: "דויד דודרה", country: "צ'כיה", club: "סלביה פראג", league: "Czech First League" },
  { name: "ינדז'יי לינגר", country: "צ'כיה", club: "פיינורד", league: "Eredivisie" },
  { name: "ואצלב צ'רני", country: "צ'כיה", club: "ריינג'רס", league: "Scottish Premiership" },
  { name: "מאטיי קובאר", country: "צ'כיה", club: "באייר לברקוזן", league: "Bundesliga" },
  { name: "פאבל שולץ", country: "צ'כיה", club: "ויקטוריה פלזן", league: "Czech First League" },
  { name: "אדם הלוז'ק", country: "צ'כיה", club: "הופנהיים", league: "Bundesliga" },
  { name: "דויד יוראסק", country: "צ'כיה", club: "הופנהיים", league: "Bundesliga" },
  { name: "יינדז'יך סטאנק", country: "צ'כיה", club: "סלביה פראג", league: "Czech First League" }
];

const GROUP_B: Player[] = [
  // קנדה
  { name: "אלפונסו דייוויס", country: "קנדה", club: "באיירן מינכן", league: "Bundesliga" },
  { name: "ג'ונתן דייוויד", country: "קנדה", club: "ליל", league: "Ligue 1" },
  { name: "איסמעאל קונה", country: "קנדה", club: "מרסיי", league: "Ligue 1" },
  { name: "סטפן אאוסטקיו", country: "קנדה", club: "פורטו", league: "Primeira Liga" },
  { name: "קייל לארין", country: "קנדה", club: "מיורקה", league: "La Liga" },
  { name: "מקסים קרפו", country: "קנדה", club: "פורטלנד טימברס", league: "MLS" },
  { name: "מויז בומביטו", country: "קנדה", club: "ניס", league: "Ligue 1" },
  { name: "דרק קורניליוס", country: "קנדה", club: "מרסיי", league: "Ligue 1" },
  { name: "ג'ונסטון אליסטר", country: "קנדה", club: "סלטיק", league: "Scottish Premiership" },
  { name: "טייג'ון ביוקנן", country: "קנדה", club: "אינטר מילאנו", league: "Serie A" },
  { name: "ג'ייקוב שאפלבורג", country: "קנדה", club: "נאשוויל", league: "MLS" },
  { name: "ליאם מילאר", country: "קנדה", club: "האל סיטי", league: "Championship" },
  { name: "ריצ'י לאריאה", country: "קנדה", club: "טורונטו", league: "MLS" },
  { name: "מת'יו שואנייר", country: "קנדה", club: "גרסהופרס", league: "Swiss Super League" },
  { name: "קמאל מילר", country: "קנדה", club: "פורטלנד טימברס", league: "MLS" },
  // בוסניה
  { name: "אדין דז'קו", country: "בוסניה", club: "פנרבחצ'ה", league: "Süper Lig" },
  { name: "ארמדין דמירוביץ'", country: "בוסניה", club: "שטוטגרט", league: "Bundesliga" },
  { name: "סיאד קולאשינאץ", country: "בוסניה", club: "אטאלנטה", league: "Serie A" },
  { name: "עמאר דדיץ'", country: "בוסניה", club: "רד בול זלצבורג", league: "Austrian Bundesliga" },
  { name: "רדה קרוניץ'", country: "בוסניה", club: "הכוכב האדום בלגרד", league: "Serbian SuperLiga" },
  { name: "אמל אהמדהוג'יץ'", country: "בוסניה", club: "שפילד יונייטד", league: "Championship" },
  { name: "יוסוף גאזיבגוביץ'", country: "בוסניה", club: "שטורם גראץ", league: "Austrian Bundesliga" },
  { name: "דניס חוסיינבשיץ'", country: "בוסניה", club: "קלן", league: "2. Bundesliga" },
  { name: "בנימין טהירוביץ'", country: "בוסניה", club: "אייאקס", league: "Eredivisie" },
  { name: "ניקולה ואסילי", country: "בוסניה", club: "סנט פאולי", league: "Bundesliga" },
  { name: "סטייפן לונצ'אר", country: "בוסניה", club: "לך פוזנן", league: "Ekstraklasa" },
  { name: "האריס היירדינוביץ'", country: "בוסניה", club: "קסימפאשה", league: "Süper Lig" },
  { name: "אדריאן לאון ברישיץ'", country: "בוסניה", club: "פ.צ. באזל", league: "Swiss Super League" },
  { name: "אניס בורניץ'", country: "בוסניה", club: "קרלסרוהה", league: "2. Bundesliga" },
  { name: "דלש קובאצ'ביץ'", country: "בוסניה", club: "ראקוב צ'נסטוחובה", league: "Ekstraklasa" },
  // קטר
  { name: "אכרם עפיף", country: "קטר", club: "אל-סאד", league: "Qatar Stars League" },
  { name: "אל-מועז עלי", country: "קטר", club: "אל-דוחייל", league: "Qatar Stars League" },
  { name: "בסאם אל-ראווי", country: "קטר", club: "אל-ריאן", league: "Qatar Stars League" },
  { name: "בועלאם ח'וח'י", country: "קטר", club: "אל-סאד", league: "Qatar Stars League" },
  { name: "לוקאס מנדס", country: "קטר", club: "אל-וכרה", league: "Qatar Stars League" },
  { name: "יוסף עבדוריסאג", country: "קטר", club: "אל-סאד", league: "Qatar Stars League" },
  { name: "חסן אל-היידוס", country: "קטר", club: "אל-סאד", league: "Qatar Stars League" },
  { name: "פדרו מיגל", country: "קטר", club: "אל-סאד", league: "Qatar Stars League" },
  { name: "אחמד פתחי", country: "קטר", club: "אל-ערבי", league: "Qatar Stars League" },
  { name: "טארק סלמאן", country: "קטר", club: "אל-סאד", league: "Qatar Stars League" },
  { name: "מוסטפא משעל", country: "קטר", club: "אל-סאד", league: "Qatar Stars League" },
  { name: "מוחמד ועאד", country: "קטר", club: "אל-סאד", league: "Qatar Stars League" },
  { name: "עבדאללה אל-אחרק", country: "קטר", club: "קטר אס.סי", league: "Qatar Stars League" },
  { name: "עיסא ברשאם", country: "קטר", club: "אל-סאד", league: "Qatar Stars League" },
  { name: "חומאם אחמד", country: "קטר", club: "אל-ע'ראפה", league: "Qatar Stars League" },
  // שווייץ
  { name: "גרניט ג'אקה", country: "שווייץ", club: "באייר לברקוזן", league: "Bundesliga" },
  { name: "מנואל אקנג'י", country: "שווייץ", club: "מנצ'סטר סיטי", league: "Premier League" },
  { name: "ברל אמבולו", country: "שווייץ", club: "מונקו", league: "Ligue 1" },
  { name: "יאן זומר", country: "שווייץ", club: "אינטר מילאנו", league: "Serie A" },
  { name: "דן אנדויה", country: "שווייץ", club: "בולוניה", league: "Serie A" },
  { name: "ריקרדו רודריגס", country: "שווייץ", club: "ריאל בטיס", league: "La Liga" },
  { name: "פביאן שר", country: "שווייץ", club: "ניוקאסל יונייטד", league: "Premier League" },
  { name: "רמו פרוילר", country: "שווייץ", club: "בולוניה", league: "Serie A" },
  { name: "רובן ורגאס", country: "שווייץ", club: "אאוגסבורג", league: "Bundesliga" },
  { name: "מישל אביישר", country: "שווייץ", club: "בולוניה", league: "Serie A" },
  { name: "גבריאל וידוביץ'", country: "שווייץ", club: "מיינץ 05", league: "Bundesliga" },
  { name: "זקי אמדוני", country: "שווייץ", club: "בנפיקה", league: "Primeira Liga" },
  { name: "ניקו אלבדי", country: "שווייץ", club: "בורוסיה מנשנגלדבך", league: "Bundesliga" },
  { name: "וינסנט סיירו", country: "שווייץ", club: "טולוז", league: "Ligue 1" },
  { name: "סילבן וידמר", country: "שווייץ", club: "מיינץ 05", league: "Bundesliga" }
];

const GROUP_C: Player[] = [
  // ברזיל
  { name: "ויניסיוס ג'וניור", country: "ברזיל", club: "ריאל מדריד", league: "La Liga" },
  { name: "רודריגו", country: "ברזיל", club: "ריאל מדריד", league: "La Liga" },
  { name: "אליסון", country: "ברזיל", club: "ליברפול", league: "Premier League" },
  { name: "אדרסון", country: "ברזיל", club: "מנצ'סטר סיטי", league: "Premier League" },
  { name: "מרקיניוס", country: "ברזיל", club: "פריז סן ז'רמן", league: "Ligue 1" },
  { name: "ברונו גימראייש", country: "ברזיל", club: "ניוקאסל יונייטד", league: "Premier League" },
  { name: "גבריאל מגאלאס", country: "ברזיל", club: "ארסנל", league: "Premier League" },
  { name: "לוקאס פאקטה", country: "ברזיל", club: "ווסטהאם יונייטד", league: "Premier League" },
  { name: "אנדריק", country: "ברזיל", club: "ריאל מדריד", league: "La Liga" },
  { name: "אדר מיליטאו", country: "ברזיל", club: "ריאל מדריד", league: "La Liga" },
  { name: "רפיניה", country: "ברזיל", club: "ברצלונה", league: "La Liga" },
  { name: "דנילו", country: "ברזיל", club: "יובנטוס", league: "Serie A" },
  { name: "סאביניו", country: "ברזיל", club: "מנצ'סטר סיטי", league: "Premier League" },
  { name: "דוגלאס לואיז", country: "ברזיל", club: "יובנטוס", league: "Serie A" },
  { name: "ז'ואאו גומס", country: "ברזיל", club: "וולברהמפטון וונדררס", league: "Premier League" },
  // מרוקו
  { name: "אשרף חכימי", country: "מרוקו", club: "פריז סן ז'רמן", league: "Ligue 1" },
  { name: "יאיא בראחים דיאס", country: "מרוקו", club: "ריאל מדריד", league: "La Liga" },
  { name: "נוסייר מזראווי", country: "מרוקו", club: "מנצ'סטר יונייטד", league: "Premier League" },
  { name: "חכים זיאש", country: "מרוקו", club: "גלאטסראיי", league: "Süper Lig" },
  { name: "סופיאן אמרבאט", country: "מרוקו", club: "פנרבחצ'ה", league: "Süper Lig" },
  { name: "יאסין בונו", country: "מרוקו", club: "אל-הילאל", league: "Saudi Pro League" },
  { name: "איברהים דיאס", country: "מרוקו", club: "ריאל מדריד", league: "La Liga" },
  { name: "יוסף א-נסירי", country: "מרוקו", club: "פנרבחצ'ה", league: "Süper Lig" },
  { name: "עז א-דין אונאחי", country: "מרוקו", club: "פנאתינייקוס", league: "Super League Greece" },
  { name: "איוב אל קעבי", country: "מרוקו", club: "אולימפיאקוס", league: "Super League Greece" },
  { name: "נאיף אגרד", country: "מרוקו", club: "ריאל סוסיאדד", league: "La Liga" },
  { name: "אמין עדלי", country: "מרוקו", club: "באייר לברקוזן", league: "Bundesliga" },
  { name: "רומן סאיס", country: "מרוקו", club: "אל-שבאב", league: "Saudi Pro League" },
  { name: "אליאס בן סע'יר", country: "מרוקו", club: "מונקו", league: "Ligue 1" },
  { name: "בילאל אל ח'נוס", country: "מרוקו", club: "לסטר סיטי", league: "Premier League" },
  // האיטי
  { name: "פרנצדי פיירו", country: "האיטי", club: "א.א.ק אתונה", league: "Super League Greece" },
  { name: "דוקנס נאזון", country: "האיטי", club: "קייסריספור", league: "Süper Lig" },
  { name: "ג'וני פלאסיד", country: "האיטי", club: "בסטיה", league: "Ligue 2" },
  { name: "ריקרדו אדה", country: "האיטי", club: "א.ד.ו. קיטו", league: "LigaPro" },
  { name: "קרלנס ארקוס", country: "האיטי", club: "אנז'ה", league: "Ligue 1" },
  { name: "דריק אטיין ג'וניור", country: "האיטי", club: "טורונטו", league: "MLS" },
  { name: "דןלי אנטואן", country: "האיטי", club: "מכבי נתניה", league: "Israeli Premier League" },
  { name: "בריאן אלסאוס", country: "האיטי", club: "דוקסה קטוקופיאס", league: "Cypriot First Division" },
  { name: "אלכס כריסטיאן", country: "האיטי", club: "וולגה אוליאנובסק", league: "Russian First League" },
  { name: "ז'אן ז'אק פייר", country: "האיטי", club: "פאריז", league: "Ligue 2" },
  { name: "קארבון ז'רייר", country: "האיטי", club: "ויבורג", league: "Danish Superliga" },
  { name: "מונדזי מארק", country: "האיטי", club: "קולורדו ראפידס", league: "MLS" },
  { name: "פבריס פיקו", country: "האיטי", club: "פילדלפיה יוניון", league: "MLS" },
  { name: "ז'וסואה דופרגה", country: "האיטי", club: "פורטימוננסה", league: "Primeira Liga" },
  { name: "זאקארי הריבו", country: "האיטי", club: "שארלוט אינדפנדנס", league: "USL League One" },
  // סקוטלנד
  { name: "אנדרו רוברטסון", country: "סקוטלנד", club: "ליברפול", league: "Premier League" },
  { name: "סקוט מקטומיניי", country: "סקוטלנד", club: "נאפולי", league: "Serie A" },
  { name: "ג'ון מקגין", country: "סקוטלנד", club: "אסטון וילה", league: "Premier League" },
  { name: "קירן טירני", country: "סקוטלנד", club: "ארסנל", league: "Premier League" },
  { name: "צ'ה אדמס", country: "סקוטלנד", club: "טורינו", league: "Serie A" },
  { name: "בילי גילמור", country: "סקוטלנד", club: "נאפולי", league: "Serie A" },
  { name: "אנגוס גאן", country: "סקוטלנד", club: "נוריץ' סיטי", league: "Championship" },
  { name: "גרנט הנלי", country: "סקוטלנד", club: "נוריץ' סיטי", league: "Championship" },
  { name: "ראיין כריסטי", country: "סקוטלנד", club: "בורנמות'", league: "Premier League" },
  { name: "סקוט מקנה", country: "סקוטלנד", club: "לאס פאלמאס", league: "La Liga" },
  { name: "ג'ק הנדרי", country: "סקוטלנד", club: "אל-איתיפאק", league: "Saudi Pro League" },
  { name: "ראיין פורטאוס", country: "סקוטלנד", club: "ווטפורד", league: "Championship" },
  { name: "אנתוני רלסטון", country: "סקוטלנד", club: "סלטיק", league: "Scottish Premiership" },
  { name: "כריס קליי", country: "סקוטלנד", club: "הארטס", league: "Scottish Premiership" },
  { name: "ג'יימס פורסט", country: "סקוטלנד", club: "סלטיק", league: "Scottish Premiership" }
];

const GROUP_D: Player[] = [
  // ארה"ב
  { name: "כריסטיאן פוליסיק", country: "ארה\"ב", club: "מילאן", league: "Serie A" },
  { name: "ווסטון מקני", country: "ארה\"ב", club: "יובנטוס", league: "Serie A" },
  { name: "פולארין באלוגון", country: "ארה\"ב", club: "מונקו", league: "Ligue 1" },
  { name: "ג'ובאני ריינה", country: "ארה\"ב", club: "בורוסיה דורטמונד", league: "Bundesliga" },
  { name: "טימותי וואה", country: "ארה\"ב", club: "יובנטוס", league: "Serie A" },
  { name: "אנטוני רובינסון", country: "ארה\"ב", club: "פולהאם", league: "Premier League" },
  { name: "סרג'יניו דסט", country: "ארה\"ב", club: "פ.ס.וו איינדהובן", league: "Eredivisie" },
  { name: "טיילר אדמס", country: "ארה\"ב", club: "בורנמות'", league: "Premier League" },
  { name: "יונוס מוסא", country: "ארה\"ב", club: "מילאן", league: "Serie A" },
  { name: "מאט טרנר", country: "ארה\"ב", club: "קריסטל פאלאס", league: "Premier League" },
  { name: "טים רים", country: "ארה\"ב", club: "שארלוט", league: "MLS" },
  { name: "כריס ריצ'רדס", country: "ארה\"ב", club: "קריסטל פאלאס", league: "Premier League" },
  { name: "קמרון קרטר-ויקרס", country: "ארה\"ב", club: "סלטיק", league: "Scottish Premiership" },
  { name: "מאליק טילמן", country: "ארה\"ב", club: "פ.ס.וו איינדהובן", league: "Eredivisie" },
  { name: "ג'וש סרג'נט", country: "ארה\"ב", club: "נוריץ' סיטי", league: "Championship" },
  // פרגוואי
  { name: "מיגל אלמירון", country: "פרגוואי", club: "ניוקאסל יונייטד", league: "Premier League" },
  { name: "חוליו אנסיסו", country: "פרגוואי", club: "ברייטון", league: "Premier League" },
  { name: "גוסטבו גומס", country: "פרגוואי", club: "פלמיירס", league: "Campeonato Brasileiro Série A" },
  { name: "מתיאס ויאסאנטי", country: "פרגוואי", club: "גרמיו", league: "Campeonato Brasileiro Série A" },
  { name: "פביאן בלבואנה", country: "פרגוואי", club: "דינמו מוסקבה", league: "Russian Premier League" },
  { name: "דייגו גומס", country: "פרגוואי", club: "אינטר מיאמי", league: "MLS" },
  { name: "רוברטו פרננדס", country: "פרגוואי", club: "דינמו מוסקבה", league: "Russian Premier League" },
  { name: "עומר אלדרטה", country: "פרגוואי", club: "חטאפה", league: "La Liga" },
  { name: "רמון סוסה", country: "פרגוואי", club: "נוטינגהאם פורסט", league: "Premier League" },
  { name: "אדם באריירו", country: "פרגוואי", club: "ריבר פלייט", league: "Argentine Primera División" },
  { name: "אלחנדרו רומרו גמארה", country: "פרגוואי", club: "אל-עין", league: "UAE Pro League" },
  { name: "קרלוס קורונל", country: "פרגוואי", club: "ניו יורק רד בולס", league: "MLS" },
  { name: "גבריאל אוואלוס", country: "פרגוואי", club: "אינדפנדיינטה", league: "Argentine Primera División" },
  { name: "מתיאס רוחאס", country: "פרגוואי", club: "אינטר מיאמי", league: "MLS" },
  { name: "אנטוני סילבה", country: "פרגוואי", club: "נסיונל", league: "Paraguayan Primera División" },
  // אוסטרליה
  { name: "מת'יו ראיין", country: "אוסטרליה", club: "רומא", league: "Serie A" },
  { name: "הארי סוטאר", country: "אוסטרליה", club: "שפילד יונייטד", league: "Championship" },
  { name: "ג'קסון ארוויין", country: "אוסטרליה", club: "סנט פאולי", league: "Bundesliga" },
  { name: "קרייג גודווין", country: "אוסטרליה", club: "אל-ווחדה", league: "Saudi Pro League" },
  { name: "מרטין בויל", country: "אוסטרליה", club: "היברניאן", league: "Scottish Premiership" },
  { name: "קיי רולס", country: "אוסטרליה", club: "הארטס", league: "Scottish Premiership" },
  { name: "קמרון בורגס", country: "אוסטרליה", club: "איפסוויץ' טאון", league: "Premier League" },
  { name: "ריילי מקגרי", country: "אוסטרליה", club: "מידלסברו", league: "Championship" },
  { name: "קונור מטקאלף", country: "אוסטרליה", club: "סנט פאולי", league: "Bundesliga" },
  { name: "קיאנו באקוס", country: "אוסטרליה", club: "מנספילד טאון", league: "EFL League One" },
  { name: "איידין חרוסטיץ'", country: "אוסטרליה", club: "סלרניטנה", league: "Serie B" },
  { name: "אזיז בהיץ'", country: "אוסטרליה", club: "מלבורן סיטי", league: "A-League" },
  { name: "מיצ'ל דיוק", country: "אוסטרליה", club: "מצ'ידה זלביה", league: "J1 League" },
  { name: "קוסייני ינגי", country: "אוסטרליה", club: "פורטסמות'", league: "Championship" },
  { name: "נתניאל אטקינסון", country: "אוסטרליה", club: "מלבורן סיטי", league: "A-League" },
  // טורקיה
  { name: "הקאן צ'להאנולו", country: "טורקיה", club: "אינטר מילאנו", league: "Serie A" },
  { name: "ארדה גולר", country: "טורקיה", club: "ריאל מדריד", league: "La Liga" },
  { name: "קנאן יילדיז", country: "טורקיה", club: "יובנטוס", league: "Serie A" },
  { name: "בארש אלפר יילמאז", country: "טורקיה", club: "גלאטסראיי", league: "Süper Lig" },
  { name: "אורקון קקצ'ו", country: "טורקיה", club: "בנפיקה", league: "Primeira Liga" },
  { name: "קארם אקטורקוגלו", country: "טורקיה", club: "בנפיקה", league: "Primeira Liga" },
  { name: "מריח דמיראל", country: "טורקיה", club: "אל-אהלי", league: "Saudi Pro League" },
  { name: "פרדי קאדיולו", country: "טורקיה", club: "ברייטון", league: "Premier League" },
  { name: "קאאן אייהאן", country: "טורקיה", club: "גלאטסראיי", league: "Süper Lig" },
  { name: "עבדולכרים ברדקצ'י", country: "טורקיה", club: "גלאטסראיי", league: "Süper Lig" },
  { name: "מרט מוולדור", country: "טורקיה", club: "פנרבחצ'ה", league: "Süper Lig" },
  { name: "מרט גונוק", country: "טורקיה", club: "בשיקטש", league: "Süper Lig" },
  { name: "איסמעיל יוקסק", country: "טורקיה", club: "פנרבחצ'ה", league: "Süper Lig" },
  { name: "צ'לאר סויונג'ו", country: "טורקיה", club: "פנרבחצ'ה", league: "Süper Lig" },
  { name: "אנאס אונאל", country: "טורקיה", club: "בורנמות'", league: "Premier League" }
];

const GROUP_E: Player[] = [
  // גרמניה
  { name: "ג'מאל מוסיאלה", country: "גרמניה", club: "באיירן מינכן", league: "Bundesliga" },
  { name: "פלוריאן וירץ", country: "גרמניה", club: "באייר לברקוזן", league: "Bundesliga" },
  { name: "קאי האברץ", country: "גרמניה", club: "ארסנל", league: "Premier League" },
  { name: "אנטוניו רודיגר", country: "גרמניה", club: "ריאל מדריד", league: "La Liga" },
  { name: "יוזואה קימיך", country: "גרמניה", club: "באיירן מינכן", league: "Bundesliga" },
  { name: "ניקלאס פילקרוג", country: "גרמניה", club: "ווסטהאם יונייטד", league: "Premier League" },
  { name: "ג'ונתן טאה", country: "גרמניה", club: "באייר לברקוזן", league: "Bundesliga" },
  { name: "ניקו שלוטרבק", country: "גרמניה", club: "בורוסיה דורטמונד", league: "Bundesliga" },
  { name: "לירוי סאנה", country: "גרמניה", club: "באיירן מינכן", league: "Bundesliga" },
  { name: "רוברט אנדריך", country: "גרמניה", club: "באייר לברקוזן", league: "Bundesliga" },
  { name: "דויד ראום", country: "גרמניה", club: "רד בול לייפציג", league: "Bundesliga" },
  { name: "פסקל גרוס", country: "גרמניה", club: "בורוסיה דורטמונד", league: "Bundesliga" },
  { name: "אלכסנדר פבלוביץ'", country: "גרמניה", club: "באיירן מינכן", league: "Bundesliga" },
  { name: "מקסמיליאן מיטלשטאדט", country: "גרמניה", club: "שטוטגרט", league: "Bundesliga" },
  { name: "מארק-אנדרה טר שטגן", country: "גרמניה", club: "ברצלונה", league: "La Liga" },
  // קוראסאו
  { name: "ג'וניניו באקונה", country: "קוראסאו", club: "אל ווחדה", league: "Saudi Pro League" },
  { name: "ליאנדרו באקונה", country: "קוראסאו", club: "חרונינגן", league: "Eredivisie" },
  { name: "אלוי רום", country: "קוראסאו", club: "ויטסה ארנהם", league: "Eerste Divisie" },
  { name: "קוקו מרטינה", country: "קוראסאו", club: "נאק ברדה", league: "Eredivisie" },
  { name: "ורנון אניטה", country: "קוראסאו", club: "אל-אורובה", league: "Saudi Pro League" },
  { name: "ירגן לוקאדיה", country: "קוראסאו", club: "אינטרספורטי", league: "Segunda División" },
  { name: "רנג'לו יאנגה", country: "קוראסאו", club: "קלוז'", league: "Liga I" },
  { name: "יוריאן גארי", country: "קוראסאו", club: "אל-חאזם", league: "Saudi First Division" },
  { name: "קנג'י גורה", country: "קוראסאו", club: "בואבישטה", league: "Primeira Liga" },
  { name: "קורנטיין כריסטיאן", country: "קוראסאו", club: "דן האג", league: "Eerste Divisie" },
  { name: "רושל ראוליסון", country: "קוראסאו", club: "ואלווייק", league: "Eredivisie" },
  { name: "גודפריד רומראטו", country: "קוראסאו", club: "הפועל תל אביב", league: "Liga Leumit" },
  { name: "קסנדרו סברינה", country: "קוראסאו", club: "פרטיזן בלגרד", league: "Serbian SuperLiga" },
  { name: "נתניאל עמנואל", country: "קוראסאו", club: "פ.צ. אמרשפורט", league: "Tweede Divisie" },
  { name: "ברנדלי קובאס", country: "קוראסאו", club: "הפועל באר שבע", league: "Israeli Premier League" },
  // חוף השנהב
  { name: "פרנק קסייה", country: "חוף השנהב", club: "אל-אהלי", league: "Saudi Pro League" },
  { name: "סבסטיאן האלר", country: "חוף השנהב", club: "לגאנס", league: "La Liga" },
  { name: "ניקולא פפה", country: "חוף השנהב", club: "ויאריאל", league: "La Liga" },
  { name: "סימון אדינגרה", country: "חוף השנהב", club: "ברייטון", league: "Premier League" },
  { name: "איבן אנדיקה", country: "חוף השנהב", club: "רומא", league: "Serie A" },
  { name: "סקו פופאנה", country: "חוף השנהב", club: "אל-איתיפאק", league: "Saudi Pro League" },
  { name: "יחיא פופאנה", country: "חוף השנהב", club: "אנז'ה", league: "Ligue 1" },
  { name: "גאסטון קונאן", country: "חוף השנהב", club: "אל-נאסר", league: "Saudi Pro League" },
  { name: "וילפריד סינגו", country: "חוף השנהב", club: "מונקו", league: "Ligue 1" },
  { name: "אוסומאן דיומנדה", country: "חוף השנהב", club: "ספורטינג ליסבון", league: "Primeira Liga" },
  { name: "ז'אן-מיקאל סרי", country: "חוף השנהב", club: "האל סיטי", league: "Championship" },
  { name: "מקס גראדל", country: "חוף השנהב", club: "סאקאריאספור", league: "TFF First League" },
  { name: "ג'ונתן במבה", country: "חוף השנהב", club: "סלטה ויגו", league: "La Liga" },
  { name: "כריסטיאן קואמה", country: "חוף השנהב", club: "פיורנטינה", league: "Serie A" },
  { name: "אודסון קוסונו", country: "חוף השנהב", club: "אטאלנטה", league: "Serie A" },
  // אקוודור
  { name: "מויסס קאייסדו", country: "אקוודור", club: "צ'לסי", league: "Premier League" },
  { name: "פיירו אינקפיה", country: "אקוודור", club: "באייר לברקוזן", league: "Bundesliga" },
  { name: "אנר ולנסיה", country: "אקוודור", club: "אינטרנסיונל", league: "Campeonato Brasileiro Série A" },
  { name: "פרביס אסטופיניאן", country: "אקוודור", club: "ברייטון", league: "Premier League" },
  { name: "קנדרי פאאס", country: "אקוודור", club: "אינדפנדיינטה דל ואיה", league: "LigaPro" },
  { name: "אלכסנדר דומינגס", country: "אקוודור", club: "א.ד.ו. קיטו", league: "LigaPro" },
  { name: "אנחלו פרסיאדו", country: "אקוודור", club: "ספרטה פראג", league: "Czech First League" },
  { name: "פליקס טורס", country: "אקוודור", club: "קורינתיאנס", league: "Campeonato Brasileiro Série A" },
  { name: "וויליאן פאצ'ו", country: "אקוודור", club: "פריז סן ז'רמן", league: "Ligue 1" },
  { name: "קרלוס גרואסו", country: "אקוודור", club: "סן חוזה ארת'קווייקס", league: "MLS" },
  { name: "ז'ואאו אורטיס", country: "אקוודור", club: "אינדפנדיינטה דל ואיה", league: "LigaPro" },
  { name: "ירמי סרמיינטו", country: "אקוודור", club: "ברנלי", league: "Championship" },
  { name: "ג'ון יבואה", country: "אקוודור", club: "ונציה", league: "Serie A" },
  { name: "קווין רודריגס", country: "אקוודור", club: "אוניון סן ז'ילואז", league: "Belgian Pro League" },
  { name: "אלן פרנקו", country: "אקוודור", club: "אתלטיקו מיניירו", league: "Campeonato Brasileiro Série A" }
];

const GROUP_F: Player[] = [
  // הולנד
  { name: "וירג'יל ואן דייק", country: "הולנד", club: "ליברפול", league: "Premier League" },
  { name: "צ'אבי סימונס", country: "הולנד", club: "רד בול לייפציג", league: "Bundesliga" },
  { name: "קודי גאקפו", country: "הולנד", club: "ליברפול", league: "Premier League" },
  { name: "פרנקי דה יונג", country: "הולנד", club: "ברצלונה", league: "La Liga" },
  { name: "נתן אקה", country: "הולנד", club: "מנצ'סטר סיטי", league: "Premier League" },
  { name: "מתיאס דה ליכט", country: "הולנד", club: "מנצ'סטר יונייטד", league: "Premier League" },
  { name: "ג'רמי פרימפונג", country: "הולנד", club: "באייר לברקוזן", league: "Bundesliga" },
  { name: "דנזל דומפריס", country: "הולנד", club: "אינטר מילאנו", league: "Serie A" },
  { name: "טייג'אני ריינדרס", country: "הולנד", club: "מילאן", league: "Serie A" },
  { name: "ג'ושוע זירקזיי", country: "הולנד", club: "מנצ'סטר יונייטד", league: "Premier League" },
  { name: "מיקי ואן דה ון", country: "הולנד", club: "טוטנהאם הוטספור", league: "Premier League" },
  { name: "בארט פרברוחן", country: "הולנד", club: "ברייטון", league: "Premier League" },
  { name: "יורדי סכאוטן", country: "הולנד", club: "פ.ס.וו איינדהובן", league: "Eredivisie" },
  { name: "סטפן דה פריי", country: "הולנד", club: "אינטר מילאנו", league: "Serie A" },
  { name: "ג'ואי פירמן", country: "הולנד", club: "פ.ס.וו איינדהובן", league: "Eredivisie" },
  // יפן
  { name: "קאורו מיטומה", country: "יפן", club: "ברייטון", league: "Premier League" },
  { name: "טקהירו טומיאסו", country: "יפן", club: "ארסנל", league: "Premier League" },
  { name: "וואטארו אנדו", country: "יפן", club: "ליברפול", league: "Premier League" },
  { name: "טקפוסה קובו", country: "יפן", club: "ריאל סוסיאדד", league: "La Liga" },
  { name: "הידמאסה מוריטה", country: "יפן", club: "ספורטינג ליסבון", league: "Primeira Liga" },
  { name: "דאיצ'י קמאדה", country: "יפן", club: "קריסטל פאלאס", league: "Premier League" },
  { name: "ריצו דואן", country: "יפן", club: "פרייבורג", league: "Bundesliga" },
  { name: "קואי איטקורה", country: "יפן", club: "בורוסיה מנשנגלדבך", league: "Bundesliga" },
  { name: "איאסה אואדה", country: "יפן", club: "פיינורד", league: "Eredivisie" },
  { name: "טאקומי מינאמינו", country: "יפן", club: "מונקו", league: "Ligue 1" },
  { name: "שוגו טאניגוצ'י", country: "יפן", club: "סנט טרוידן", league: "Belgian Pro League" },
  { name: "זיאון סוזוקי", country: "יפן", club: "פארמה", league: "Serie A" },
  { name: "יוקינארי סוגאווארה", country: "יפן", club: "סאותהמפטון", league: "Premier League" },
  { name: "גנקי הראגוצ'י", country: "יפן", club: "אוראווה רד דיימונדס", league: "J1 League" },
  { name: "קייטו נקאמורה", country: "יפן", club: "ריימס", league: "Ligue 1" },
  // שוודיה
  { name: "ויקטור גיוקרס", country: "שוודיה", club: "ספורטינג ליסבון", league: "Primeira Liga" },
  { name: "אלכסנדר איסאק", country: "שוודיה", club: "ניוקאסל יונייטד", league: "Premier League" },
  { name: "דיאן קולוסבסקי", country: "שוודיה", club: "טוטנהאם הוטספור", league: "Premier League" },
  { name: "ויקטור לינדלף", country: "שוודיה", club: "מנצ'סטר יונייטד", league: "Premier League" },
  { name: "אנתוני אלנגה", country: "שוודיה", club: "נוטינגהאם פורסט", league: "Premier League" },
  { name: "יספר קרלסון", country: "שוודיה", club: "בולוניה", league: "Serie A" },
  { name: "רובין אולסן", country: "שוודיה", club: "אסטון וילה", league: "Premier League" },
  { name: "מתיאס סוונברג", country: "שוודיה", club: "וולפסבורג", league: "Bundesliga" },
  { name: "ינס קאיוסטה", country: "שוודיה", club: "איפסוויץ' טאון", league: "Premier League" },
  { name: "הוגו לארסון", country: "שוודיה", club: "איינטרכט פרנקפורט", league: "Bundesliga" },
  { name: "לוקאס ברגוואל", country: "שוודיה", club: "טוטנהאם הוטספור", league: "Premier League" },
  { name: "אמיל קראפט", country: "שוודיה", club: "ניוקאסל יונייטד", league: "Premier League" },
  { name: "גבריאל גודמונדסון", country: "שוודיה", club: "ליל", league: "Ligue 1" },
  { name: "אמיל הולם", country: "שוודיה", club: "בולוניה", league: "Serie A" },
  { name: "לודוויג אוגוסטינסון", country: "שוודיה", club: "אנדרלכט", league: "Belgian Pro League" },
  // תוניסיה
  { name: "יוסף אל-מסאכני", country: "תוניסיה", club: "אל-ערבי", league: "Qatar Stars League" },
  { name: "אליאס סח'ירי", country: "תוניסיה", club: "איינטרכט פרנקפורט", league: "Bundesliga" },
  { name: "איסא לאידוני", country: "תוניסיה", club: "אל-וכרה", league: "Qatar Stars League" },
  { name: "מונתסר טאלבי", country: "תוניסיה", club: "לוריאן", league: "Ligue 2" },
  { name: "אליאס עאשורי", country: "תוניסיה", club: "פ.צ. קופנהגן", league: "Danish Superliga" },
  { name: "סייפדינה ג'זירי", country: "תוניסיה", club: "זמאלק", league: "Egyptian Premier League" },
  { name: "יאסין מריאח", country: "תוניסיה", club: "אספרנס", league: "Tunisian Ligue Professionnelle 1" },
  { name: "חמזה רפיע", country: "תוניסיה", club: "לצ'ה", league: "Serie A" },
  { name: "נאדר ע'נדרי", country: "תוניסיה", club: "אחמט גרוזני", league: "Russian Premier League" },
  { name: "עלי עבדי", country: "תוניסיה", club: "ניס", league: "Ligue 1" },
  { name: "מוחמד עלי בן רמדאן", country: "תוניסיה", club: "פרנצווארוש", league: "Nemzeti Bajnokság I" },
  { name: "איימן דחמאן", country: "תוניסיה", club: "ספקסיאן", league: "Tunisian Ligue Professionnelle 1" },
  { name: "חנבעל מג'ברי", country: "תוניסיה", club: "ברנלי", league: "Championship" },
  { name: "וג'די קשרידה", country: "תוניסיה", club: "אל-ע'ראפה", league: "Qatar Stars League" },
  { name: "אניס בן סלימאן", country: "תוניסיה", club: "נוריץ' סיטי", league: "Championship" }
];

const GROUP_G: Player[] = [
  // בלגיה
  { name: "קווין דה בראונה", country: "בלגיה", club: "מנצ'סטר סיטי", league: "Premier League" },
  { name: "רומלו לוקאקו", country: "בלגיה", club: "נאפולי", league: "Serie A" },
  { name: "ז'רמי דוקו", country: "בלגיה", club: "מנצ'סטר סיטי", league: "Premier League" },
  { name: "לאנדרו טרוסאר", country: "בלגיה", club: "ארסנל", league: "Premier League" },
  { name: "אמאדו אונאנה", country: "בלגיה", club: "אסטון וילה", league: "Premier League" },
  { name: "לואיס אופנדה", country: "בלגיה", club: "רד בול לייפציג", league: "Bundesliga" },
  { name: "טימותי קסטאן", country: "בלגיה", club: "פולהאם", league: "Premier League" },
  { name: "יוהאן באקאיוקו", country: "בלגיה", club: "פ.ס.וו איינדהובן", league: "Eredivisie" },
  { name: "ואוט פאאס", country: "בלגיה", club: "לסטר סיטי", league: "Premier League" },
  { name: "קון קסטילס", country: "בלגיה", club: "אל-קאדסיה", league: "Saudi Pro League" },
  { name: "יורי טילמנס", country: "בלגיה", club: "אסטון וילה", league: "Premier League" },
  { name: "ארתור תיאט", country: "בלגיה", club: "איינטרכט פרנקפורט", league: "Bundesliga" },
  { name: "אורל מנגאלה", country: "בלגיה", club: "אברטון", league: "Premier League" },
  { name: "יאניק קראסקו", country: "בלגיה", club: "אל-שבאב", league: "Saudi Pro League" },
  { name: "צ'ארלס דה קטלארה", country: "בלגיה", club: "אטאלנטה", league: "Serie A" },
  // מצרים
  { name: "מוחמד סלאח", country: "מצרים", club: "ליברפול", league: "Premier League" },
  { name: "מוסטפא מוחמד", country: "מצרים", club: "נאנט", league: "Ligue 1" },
  { name: "עומר מרמוש", country: "מצרים", club: "איינטרכט פרנקפורט", league: "Bundesliga" },
  { name: "מחמוד טרזגה", country: "מצרים", club: "אל-ריאן", league: "Qatar Stars League" },
  { name: "מוחמד אלנני", country: "מצרים", club: "אל ג'זירה", league: "UAE Pro League" },
  { name: "אחמד חגאזי", country: "מצרים", club: "נאום", league: "Saudi First Division" },
  { name: "מוחמד א-שנאווי", country: "מצרים", club: "אל אהלי", league: "Egyptian Premier League" },
  { name: "אחמד סייד", country: "מצרים", club: "זמאלק", league: "Egyptian Premier League" },
  { name: "אמאם עאשור", country: "מצרים", club: "אל אהלי", league: "Egyptian Premier League" },
  { name: "עבד אל-מונעם", country: "מצרים", club: "ניס", league: "Ligue 1" },
  { name: "רמי רביעה", country: "מצרים", club: "אל אהלי", league: "Egyptian Premier League" },
  { name: "מרואן עטיה", country: "מצרים", club: "אל אהלי", league: "Egyptian Premier League" },
  { name: "מוחמד עבד א-מונעם", country: "מצרים", club: "אל אהלי", league: "Egyptian Premier League" },
  { name: "אחמד נביל קוקה", country: "מצרים", club: "אל אהלי", league: "Egyptian Premier League" },
  { name: "מוסטפא פתחי", country: "מצרים", club: "פירמידה", league: "Egyptian Premier League" },
  // איראן
  { name: "מהדי טארמי", country: "איראן", club: "אינטר מילאנו", league: "Serie A" },
  { name: "סרדאר אזמון", country: "איראן", club: "שבאב אל-אהלי", league: "UAE Pro League" },
  { name: "אלירזה ג'האנבאחש", country: "איראן", club: "הירנביין", league: "Eredivisie" },
  { name: "אלירזה ביירנבאנד", country: "איראן", club: "טרקטור סאזי", league: "Persian Gulf Pro League" },
  { name: "סמאן קודוס", country: "איראן", club: "כלבה", league: "UAE Pro League" },
  { name: "סעיד עזת-אללהי", country: "איראן", club: "שבאב אל-אהלי", league: "UAE Pro League" },
  { name: "שוג'אע חלילזאדה", country: "איראן", club: "טרקטור סאזי", league: "Persian Gulf Pro League" },
  { name: "רמין רזאיאן", country: "איראן", club: "אסתקלאל תהראן", league: "Persian Gulf Pro League" },
  { name: "מהדי ע'אידי", country: "איראן", club: "אל-איתיחאד קלבה", league: "UAE Pro League" },
  { name: "סאדג מוחרמי", country: "איראן", club: "דינמו זאגרב", league: "Prva HNL" },
  { name: "חוסיין קנעאניזאדגן", country: "איראן", club: "פרספוליס", league: "Persian Gulf Pro League" },
  { name: "מוחמד מוחבי", country: "איראן", club: "רוסטוב", league: "Russian Premier League" },
  { name: "אלי גוליזאדה", country: "איראן", club: "לך פוזנן", league: "Ekstraklasa" },
  { name: "רוזבה צ'שמי", country: "איראן", club: "אסתקלאל תהראן", league: "Persian Gulf Pro League" },
  { name: "מילאד מוחמדי", country: "איראן", club: "פרספוליס", league: "Persian Gulf Pro League" },
  // ניו זילנד
  { name: "כריס ווד", country: "ניו זילנד", club: "נוטינגהאם פורסט", league: "Premier League" },
  { name: "מרקו רוחאס", country: "ניו זילנד", club: "בריזבן רואר", league: "A-League" },
  { name: "ליבראטו קקאצ'ה", country: "ניו זילנד", club: "אמפולי", league: "Serie A" },
  { name: "ג'ו בל", country: "ניו זילנד", club: "ויקינג", league: "Eliteserien" },
  { name: "מתיו גרבט", country: "ניו זילנד", club: "נאק ברדה", league: "Eredivisie" },
  { name: "קאלום אליוט", country: "ניו זילנד", club: "אוקלנד סיטי", league: "New Zealand National League" },
  { name: "קונסטנטינוס ברברוסס", country: "ניו זילנד", club: "ולינגטון פיניקס", league: "A-League" },
  { name: "מקס קרוקומב", country: "ניו זילנד", club: "ברטון אלביון", league: "EFL League One" },
  { name: "נאנדו פיינקר", country: "ניו זילנד", club: "סליגו רוברס", league: "League of Ireland Premier Division" },
  { name: "אלכס רופר", country: "ניו זילנד", club: "ולינגטון פיניקס", league: "A-League" },
  { name: "דיין אינגהאם", country: "ניו זילנד", club: "ניוקאסל ג'טס", league: "A-League" },
  { name: "אליג'ה ג'אסט", country: "ניו זילנד", club: "סנט פולטן", league: "2. Liga" },
  { name: "מייקל בוקסל", country: "ניו זילנד", club: "מינסוטה יונייטד", league: "MLS" },
  { name: "אוליבר סייל", country: "ניו זילנד", club: "מלבורן ויקטורי", league: "A-League" },
  { name: "בן ויין", country: "ניו זילנד", club: "צ'רלטון אתלטיק", league: "EFL League One" }
];

const GROUP_H: Player[] = [
  // ספרד
  { name: "לאמין ימאל", country: "ספרד", club: "ברצלונה", league: "La Liga" },
  { name: "רודרי", country: "ספרד", club: "מנצ'סטר סיטי", league: "Premier League" },
  { name: "פדרי", country: "ספרד", club: "ברצלונה", league: "La Liga" },
  { name: "ניקו ויליאמס", country: "ספרד", club: "אתלטיק בילבאו", league: "La Liga" },
  { name: "דני אולמו", country: "ספרד", club: "ברצלונה", league: "La Liga" },
  { name: "פביאן רואיס", country: "ספרד", club: "פריז סן ז'רמן", league: "Ligue 1" },
  { name: "דני קרבחאל", country: "ספרד", club: "ריאל מדריד", league: "La Liga" },
  { name: "אלברו מוראטה", country: "ספרד", club: "מילאן", league: "Serie A" },
  { name: "איימריק לאפורט", country: "ספרד", club: "אל-נאסר", league: "Saudi Pro League" },
  { name: "אונאי סימון", country: "ספרד", club: "אתלטיק בילבאו", league: "La Liga" },
  { name: "מרק קוקורייה", country: "ספרד", club: "צ'לסי", league: "Premier League" },
  { name: "רובין לה נורמן", country: "ספרד", club: "אתלטיקו מדריד", league: "La Liga" },
  { name: "מרטין סובימנדי", country: "ספרד", club: "ריאל סוסיאדד", league: "La Liga" },
  { name: "מיקל אויארסבאל", country: "ספרד", club: "ריאל סוסיאדד", league: "La Liga" },
  { name: "דויד ראיה", country: "ספרד", club: "ארסנל", league: "Premier League" },
  // כף ורדה
  { name: "גארי רודריגס", country: "כף ורדה", club: "סיוואספור", league: "Süper Lig" },
  { name: "ראיין מנדס", country: "כף ורדה", club: "קוג'אליספור", league: "TFF First League" },
  { name: "לוגאן קוסטה", country: "כף ורדה", club: "ויאריאל", league: "La Liga" },
  { name: "בבה", country: "כף ורדה", club: "ראסינג פרול", league: "Segunda División" },
  { name: "רוברטו לופס", country: "כף ורדה", club: "שמרוק רוברס", league: "League of Ireland Premier Division" },
  { name: "חובאנה קבראל", country: "כף ורדה", club: "אסטרלה דה אמדורה", league: "Primeira Liga" },
  { name: "זואו פאולו", country: "כף ורדה", club: "שריף טירספול", league: "Moldovan Super Liga" },
  { name: "פיקו", country: "כף ורדה", club: "קראקס", league: "Venezuelan Primera División" },
  { name: "דירה", country: "כף ורדה", club: "ווילם II", league: "Eredivisie" },
  { name: "ז'אנירו מונטיירו", country: "כף ורדה", club: "סן חוזה ארת'קווייקס", league: "MLS" },
  { name: "קווין פינה", country: "כף ורדה", club: "קרסנודאר", league: "Russian Premier League" },
  { name: "דוקנס מואנז", country: "כף ורדה", club: "היידנהיים", league: "Bundesliga" },
  { name: "סטיבן מוריירה", country: "כף ורדה", club: "קולומבוס קרו", league: "MLS" },
  { name: "דלמירו", country: "כף ורדה", club: "אינדיפנדיינטה", league: "Argentine Primera División" },
  { name: "ווזניה", country: "כף ורדה", club: "אראד", league: "Liga I" },
  // סעודיה
  { name: "סאלם א-דאווסרי", country: "סעודיה", club: "אל-הילאל", league: "Saudi Pro League" },
  { name: "סעוד עבד אל-חמיד", country: "סעודיה", club: "רומא", league: "Serie A" },
  { name: "מוחמד כנו", country: "סעודיה", club: "אל-הילאל", league: "Saudi Pro League" },
  { name: "פרס אל-בורייכאן", country: "סעודיה", club: "אל-אהלי", league: "Saudi Pro League" },
  { name: "עלי אל-בולייהי", country: "סעודיה", club: "אל-הילאל", league: "Saudi Pro League" },
  { name: "יאסר א-שהראני", country: "סעודיה", club: "אל-הילאל", league: "Saudi Pro League" },
  { name: "עבד א-רחמן ע'ריב", country: "סעודיה", club: "אל-נאסר", league: "Saudi Pro League" },
  { name: "סמי א-נג'עי", country: "סעודיה", club: "אל-נאסר", league: "Saudi Pro League" },
  { name: "סאלח א-שהרי", country: "סעודיה", club: "אל-איתיחאד", league: "Saudi Pro League" },
  { name: "מוחמד אל-עוויס", country: "סעודיה", club: "אל-הילאל", league: "Saudi Pro League" },
  { name: "נוואף אל-עקידי", country: "סעודיה", club: "אל-נאסר", league: "Saudi Pro League" },
  { name: "חסן תמבקתי", country: "סעודיה", club: "אל-הילאל", league: "Saudi Pro League" },
  { name: "עבדאללה אל-ח'ייברי", country: "סעודיה", club: "אל-נאסר", league: "Saudi Pro League" },
  { name: "סולטאן אל-ע'נאם", country: "סעודיה", club: "אל-נאסר", league: "Saudi Pro League" },
  { name: "אימן יחיא", country: "סעודיה", club: "אל-נאסר", league: "Saudi Pro League" },
  // אורוגוואי
  { name: "פדריקו ואלוורדה", country: "אורוגוואי", club: "ריאל מדריד", league: "La Liga" },
  { name: "דרווין נונייס", country: "אורוגוואי", club: "ליברפול", league: "Premier League" },
  { name: "רונאלד אראוחו", country: "אורוגוואי", club: "ברצלונה", league: "La Liga" },
  { name: "מנואל אוגארטה", country: "אורוגוואי", club: "מנצ'סטר יונייטד", league: "Premier League" },
  { name: "רודריגו בנטנקור", country: "אורוגוואי", club: "טוטנהאם הוטספור", league: "Premier League" },
  { name: "חוסה מריה חימנס", country: "אורוגוואי", club: "אתלטיקו מדריד", league: "La Liga" },
  { name: "ניקולס דה לה קרוס", country: "אורוגוואי", club: "פלמיירס", league: "Campeonato Brasileiro Série A" },
  { name: "מקסימיליאנו אראוחו", country: "אורוגוואי", club: "ספורטינג ליסבון", league: "Primeira Liga" },
  { name: "פקונדו פליסטרי", country: "אורוגוואי", club: "פנאתינייקוס", league: "Super League Greece" },
  { name: "סרחיו רוצ'ט", country: "אורוגוואי", club: "אינטרנסיונל", league: "Campeonato Brasileiro Série A" },
  { name: "נאיתן נאנדס", country: "אורוגוואי", club: "אל-קאדסיה", league: "Saudi Pro League" },
  { name: "מתאס אוליברה", country: "אורוגוואי", club: "נאפולי", league: "Serie A" },
  { name: "מתיאס וינייה", country: "אורוגוואי", club: "פלמנגו", league: "Campeonato Brasileiro Série A" },
  { name: "גיז'רמו וארלה", country: "אורוגוואי", club: "פלמנגו", league: "Campeonato Brasileiro Série A" },
  { name: "פקונדו טורס", country: "אורוגוואי", club: "אורלנדו סיטי", league: "MLS" }
];

const GROUP_I: Player[] = [
  // צרפת
  { name: "קיליאן אמבפה", country: "צרפת", club: "ריאל מדריד", league: "La Liga" },
  { name: "אורליאן צ'ואמני", country: "צרפת", club: "ריאל מדריד", league: "La Liga" },
  { name: "עוסמאן דמבלה", country: "צרפת", club: "פריז סן ז'רמן", league: "Ligue 1" },
  { name: "וויליאם סאליבה", country: "צרפת", club: "ארסנל", league: "Premier League" },
  { name: "אדוארדו קמאבינגה", country: "צרפת", club: "ריאל מדריד", league: "La Liga" },
  { name: "תיאו הרננדס", country: "צרפת", club: "מילאן", league: "Serie A" },
  { name: "מייק מניאן", country: "צרפת", club: "מילאן", league: "Serie A" },
  { name: "דאיו אופאמקאנו", country: "צרפת", club: "באיירן מינכן", league: "Bundesliga" },
  { name: "איברהימה קונאטה", country: "צרפת", club: "ליברפול", league: "Premier League" },
  { name: "ז'ול קונדה", country: "צרפת", club: "ברצלונה", league: "La Liga" },
  { name: "אנגולו קאנטה", country: "צרפת", club: "אל-איתיחאד", league: "Saudi Pro League" },
  { name: "בראדלי ברקולה", country: "צרפת", club: "פריז סן ז'רמן", league: "Ligue 1" },
  { name: "רנדאל קולו מואני", country: "צרפת", club: "פריז סן ז'רמן", league: "Ligue 1" },
  { name: "מרקוס תוראם", country: "צרפת", club: "אינטר מילאנו", league: "Serie A" },
  { name: "וורן זאיר-אמרי", country: "צרפת", club: "פריז סן ז'רמן", league: "Ligue 1" },
  // סנגל
  { name: "סאדיו מאנה", country: "סנגל", club: "אל-נאסר", league: "Saudi Pro League" },
  { name: "קאלידו קוליבאלי", country: "סנגל", club: "אל-הילאל", league: "Saudi Pro League" },
  { name: "אדואר מנדי", country: "סנגל", club: "אל-אהלי", league: "Saudi Pro League" },
  { name: "אידריסה גואה", country: "סנגל", club: "אברטון", league: "Premier League" },
  { name: "איסמעילה סאר", country: "סנגל", club: "קריסטל פאלאס", league: "Premier League" },
  { name: "פאפ מאטאר סאר", country: "סנגל", club: "טוטנהאם הוטספור", league: "Premier League" },
  { name: "ניקולס ג'קסון", country: "סנגל", club: "צ'לסי", league: "Premier League" },
  { name: "חביב דיאלו", country: "סנגל", club: "דמאכ", league: "Saudi Pro League" },
  { name: "בולה דיא", country: "סנגל", club: "לאציו", league: "Serie A" },
  { name: "עבדו דיאלו", country: "סנגל", club: "אל-ערבי", league: "Qatar Stars League" },
  { name: "מוסא ניאחאטה", country: "סנגל", club: "אולימפיק ליון", league: "Ligue 1" },
  { name: "איסמעיל ג'ייקובס", country: "סנגל", club: "גלאטסראיי", league: "Süper Lig" },
  { name: "נמפליס מנדי", country: "סנגל", club: "לאנס", league: "Ligue 1" },
  { name: "קרפין דיאטה", country: "סנגל", club: "מונקו", league: "Ligue 1" },
  { name: "אילמן אנדיאייה", country: "סנגל", club: "אברטון", league: "Premier League" },
  // עיראק
  { name: "אימן חוסיין", country: "עיראק", club: "אל קורס", league: "Qatar Stars League" },
  { name: "עלי ג'אסם", country: "עיראק", club: "קומו", league: "Serie A" },
  { name: "אמג'ד עטוואן", country: "עיראק", club: "זאכו", league: "Iraq Stars League" },
  { name: "זידאן איקבל", country: "עיראק", club: "אוטרכט", league: "Eredivisie" },
  { name: "מוהנד עלי", country: "עיראק", club: "אל-שורטה", league: "Iraq Stars League" },
  { name: "עלי עדנאן", country: "עיראק", club: "מס רפסנג'אן", league: "Persian Gulf Pro League" },
  { name: "אוסמה רשיד", country: "עיראק", club: "אירביל", league: "Iraq Stars League" },
  { name: "פרנצ'ס פוטרוס", country: "עיראק", club: "פורט", league: "Thai League 1" },
  { name: "מרחאס דוסקי", country: "עיראק", club: "סלובצקו", league: "Czech First League" },
  { name: "איברהים באיש", country: "עיראק", club: "אל-ריאד", league: "Saudi Pro League" },
  { name: "חוסיין עלי", country: "עיראק", club: "הירנביין", league: "Eredivisie" },
  { name: "מוסטפא נאדים", country: "עיראק", club: "אל-זאוראה", league: "Iraq Stars League" },
  { name: "באשאר רסאן", country: "עיראק", club: "אל-מרחייה", league: "Qatar Stars League" },
  { name: "ג'לאל חסן", country: "עיראק", club: "אל-זאוראה", league: "Iraq Stars League" },
  { name: "רבין סולאקה", country: "עיראק", club: "שפילד ונסדיי", league: "Championship" },
  // נורווגיה
  { name: "ארלינג הולאנד", country: "נורווגיה", club: "מנצ'סטר סיטי", league: "Premier League" },
  { name: "מרטין אודגור", country: "נורווגיה", club: "ארסנל", league: "Premier League" },
  { name: "אלכסנדר סורלות", country: "נורווגיה", club: "אתלטיקו מדריד", league: "La Liga" },
  { name: "אנטוניו נוסא", country: "נורווגיה", club: "רד בול לייפציג", league: "Bundesliga" },
  { name: "יורגן סטרנד לארסן", country: "נורווגיה", club: "וולברהמפטון וונדררס", league: "Premier League" },
  { name: "סנדר ברגה", country: "נורווגיה", club: "פולהאם", league: "Premier League" },
  { name: "יוליאן ריירסון", country: "נורווגיה", club: "בורוסיה דורטמונד", league: "Bundesliga" },
  { name: "לאו אוסטיגור", country: "נורווגיה", club: "ראן", league: "Ligue 1" },
  { name: "אוסקר בוב", country: "נורווגיה", club: "מנצ'סטר סיטי", league: "Premier League" },
  { name: "פטריק ברג", country: "נורווגיה", club: "בודה/גלימט", league: "Eliteserien" },
  { name: "כריסטופר אייר", country: "נורווגיה", club: "ברנטפורד", league: "Premier League" },
  { name: "אוריין ניילנד", country: "נורווגיה", club: "סביליה", league: "La Liga" },
  { name: "הוגו וטלסן", country: "נורווגיה", club: "קלאב ברוז'", league: "Belgian Pro League" },
  { name: "דויד מולר קנאוטסן", country: "נורווגיה", club: "וולפסבורג", league: "Bundesliga" },
  { name: "אנדראס שיידרופ", country: "נורווגיה", club: "בנפיקה", league: "Primeira Liga" }
];

const GROUP_J: Player[] = [
  // ארגנטינה
  { name: "ליונל מסי", country: "ארגנטינה", club: "אינטר מיאמי", league: "MLS" },
  { name: "לאוטרו מרטינס", country: "ארגנטינה", club: "אינטר מילאנו", league: "Serie A" },
  { name: "חוליאן אלברס", country: "ארגנטינה", club: "אתלטיקו מדריד", league: "La Liga" },
  { name: "אלכסיס מק אליסטר", country: "ארגנטינה", club: "ליברפול", league: "Premier League" },
  { name: "רודריגו דה פול", country: "ארגנטינה", club: "אתלטיקו מדריד", league: "La Liga" },
  { name: "אנסו פרננדס", country: "ארגנטינה", club: "צ'לסי", league: "Premier League" },
  { name: "אמיליאנו מרטינס", country: "ארגנטינה", club: "אסטון וילה", league: "Premier League" },
  { name: "כריסטיאן רומרו", country: "ארגנטינה", club: "טוטנהאם הוטספור", league: "Premier League" },
  { name: "ליסנדרו מרטינס", country: "ארגנטינה", club: "מנצ'סטר יונייטד", league: "Premier League" },
  { name: "ניקולס אוטמנדי", country: "ארגנטינה", club: "בנפיקה", league: "Primeira Liga" },
  { name: "נהואל מולינה", country: "ארגנטינה", club: "אתלטיקו מדריד", league: "La Liga" },
  { name: "אלחנדרו גרנאצ'ו", country: "ארגנטינה", club: "מנצ'סטר יונייטד", league: "Premier League" },
  { name: "ג'ובאני לו צ'לסו", country: "ארגנטינה", club: "ריאל בטיס", league: "La Liga" },
  { name: "ניקולס גונסאלס", country: "ארגנטינה", club: "יובנטוס", league: "Serie A" },
  { name: "פאולו דיבאלה", country: "ארגנטינה", club: "רומא", league: "Serie A" },
  // אלג'יריה
  { name: "ריאד מחרז", country: "אלג'יריה", club: "אל-אהלי", league: "Saudi Pro League" },
  { name: "אסמאעיל בן נאצר", country: "אלג'יריה", club: "מילאן", league: "Serie A" },
  { name: "סעיד בנרחמה", country: "אלג'יריה", club: "אולימפיק ליון", league: "Ligue 1" },
  { name: "רמי בנסבאיני", country: "אלג'יריה", club: "בורוסיה דורטמונד", league: "Bundesliga" },
  { name: "חוסם עוואר", country: "אלג'יריה", club: "אל-איתיחאד", league: "Saudi Pro League" },
  { name: "ראמי שייבי", country: "אלג'יריה", club: "איינטרכט פרנקפורט", league: "Bundesliga" },
  { name: "אמין גואירי", country: "אלג'יריה", club: "ראן", league: "Ligue 1" },
  { name: "מוחמד אמורה", country: "אלג'יריה", club: "וולפסבורג", league: "Bundesliga" },
  { name: "יוסף עטאל", country: "אלג'יריה", club: "אל-סאד", league: "Qatar Stars League" },
  { name: "עיסא מאנדי", country: "אלג'יריה", club: "ליל", league: "Ligue 1" },
  { name: "ראמז זרוקי", country: "אלג'יריה", club: "פיינורד", league: "Eredivisie" },
  { name: "אנתוני מנדריאה", country: "אלג'יריה", club: "קאן", league: "Ligue 2" },
  { name: "באגדד בונג'אח", country: "אלג'יריה", club: "אל-שמאל", league: "Qatar Stars League" },
  { name: "ראיין אית-נורי", country: "אלג'יריה", club: "וולברהמפטון וונדררס", league: "Premier League" },
  { name: "נביל בנטאלב", country: "אלג'יריה", club: "ליל", league: "Ligue 1" },
  // אוסטריה
  { name: "דויד אלאבה", country: "אוסטריה", club: "ריאל מדריד", league: "La Liga" },
  { name: "מרסל סביצר", country: "אוסטריה", club: "בורוסיה דורטמונד", league: "Bundesliga" },
  { name: "קונרד ליימר", country: "אוסטריה", club: "באיירן מינכן", league: "Bundesliga" },
  { name: "מרקו ארנאוטוביץ'", country: "אוסטריה", club: "אינטר מילאנו", league: "Serie A" },
  { name: "כריסטוף באומגרטנר", country: "אוסטריה", club: "רד בול לייפציג", league: "Bundesliga" },
  { name: "מיכאל גרגוריטש", country: "אוסטריה", club: "פרייבורג", league: "Bundesliga" },
  { name: "שטפן פוש", country: "אוסטריה", club: "בולוניה", league: "Serie A" },
  { name: "קווין דאנזו", country: "אוסטריה", club: "לאנס", league: "Ligue 1" },
  { name: "קסאבר שלאגר", country: "אוסטריה", club: "רד בול לייפציג", league: "Bundesliga" },
  { name: "ניקולס זייוולד", country: "אוסטריה", club: "רד בול לייפציג", league: "Bundesliga" },
  { name: "מקסימיליאן ובר", country: "אוסטריה", club: "לידס יונייטד", league: "Championship" },
  { name: "אלכסנדר שלאגר", country: "אוסטריה", club: "רד בול זלצבורג", league: "Austrian Bundesliga" },
  { name: "פיליפ לינהארט", country: "אוסטריה", club: "פרייבורג", league: "Bundesliga" },
  { name: "פטריק וימר", country: "אוסטריה", club: "וולפסבורג", league: "Bundesliga" },
  { name: "רומנו שמיד", country: "אוסטריה", club: "ורדר ברמן", league: "Bundesliga" },
  // ירדן
  { name: "מוסא אל-תעמרי", country: "ירדן", club: "מונפלייה", league: "Ligue 1" },
  { name: "יאזאן א-נעימאת", country: "ירדן", club: "אל-ערבי", league: "Qatar Stars League" },
  { name: "מחמוד אל-מרדי", country: "ירדן", club: "אל חוסיין אירביד", league: "Jordanian Pro League" },
  { name: "עלי אולוואן", country: "ירדן", club: "סלנגור", league: "Malaysia Super League" },
  { name: "יאזאן אל-ערב", country: "ירדן", club: "פ.צ. סיאול", league: "K League 1" },
  { name: "איחסאן חדאד", country: "ירדן", club: "אל חוסיין אירביד", league: "Jordanian Pro League" },
  { name: "נזאר אל-רשדאן", country: "ירדן", club: "אל-פיסאלי", league: "Jordanian Pro League" },
  { name: "עבדאללה נסיב", country: "ירדן", club: "אל חוסיין אירביד", league: "Jordanian Pro League" },
  { name: "נור אל-רוואבדה", country: "ירדן", club: "סלנגור", league: "Malaysia Super League" },
  { name: "יאזיד אבו ליילא", country: "ירדן", club: "אל-חאזם", league: "Saudi First Division" },
  { name: "מוחמד אבו חשיש", country: "ירדן", club: "אל-עאהד", league: "Lebanese Premier League" },
  { name: "ראג'אעי עאיד", country: "ירדן", club: "אל חוסיין אירביד", league: "Jordanian Pro League" },
  { name: "סאלם אל-עג'אלין", country: "ירדן", club: "אל-פיסאלי", league: "Jordanian Pro League" },
  { name: "איבראהים סעאדה", country: "ירדן", club: "אל חוסיין אירביד", league: "Jordanian Pro League" },
  { name: "ענאס בני יאסין", country: "ירדן", club: "אל-פיסאלי", league: "Jordanian Pro League" }
];

const GROUP_K: Player[] = [
  // פורטוגל
  { name: "כריסטיאנו רונאלדו", country: "פורטוגל", club: "אל-נאסר", league: "Saudi Pro League" },
  { name: "ברונו פרננדס", country: "פורטוגל", club: "מנצ'סטר יונייטד", league: "Premier League" },
  { name: "ברנרדו סילבה", country: "פורטוגל", club: "מנצ'סטר סיטי", league: "Premier League" },
  { name: "רפאל לאאו", country: "פורטוגל", club: "מילאן", league: "Serie A" },
  { name: "רובן דיאש", country: "פורטוגל", club: "מנצ'סטר סיטי", league: "Premier League" },
  { name: "ז'ואאו קאנסלו", country: "פורטוגל", club: "אל-הילאל", league: "Saudi Pro League" },
  { name: "דיוגו ז'וטה", country: "פורטוגל", club: "ליברפול", league: "Premier League" },
  { name: "ז'ואאו פליקס", country: "פורטוגל", club: "צ'לסי", league: "Premier League" },
  { name: "דיוגו קוסטה", country: "פורטוגל", club: "פורטו", league: "Primeira Liga" },
  { name: "ויטיניה", country: "פורטוגל", club: "פריז סן ז'רמן", league: "Ligue 1" },
  { name: "ז'ואאו פלהיניה", country: "פורטוגל", club: "באיירן מינכן", league: "Bundesliga" },
  { name: "נונו מנדס", country: "פורטוגל", club: "פריז סן ז'רמן", league: "Ligue 1" },
  { name: "דיוגו דאלוט", country: "פורטוגל", club: "מנצ'סטר יונייטד", league: "Premier League" },
  { name: "גונסאלו ראמוס", country: "פורטוגל", club: "פריז סן ז'רמן", league: "Ligue 1" },
  { name: "גונסאלו אינסיו", country: "פורטוגל", club: "ספורטינג ליסבון", league: "Primeira Liga" },
  // קונגו (הדמוקרטית)
  { name: "שאנסל אמבמבה", country: "קונגו", club: "מרסיי", league: "Ligue 1" },
  { name: "יואן וויסה", country: "קונגו", club: "ברנטפורד", league: "Premier League" },
  { name: "משיאק אליה", country: "קונגו", club: "יאנג בויז", league: "Swiss Super League" },
  { name: "ארתור מסואקו", country: "קונגו", club: "בשיקטש", league: "Süper Lig" },
  { name: "תיאו בונגונדה", country: "קונגו", club: "ספרטק מוסקבה", league: "Russian Premier League" },
  { name: "סימון באנזה", country: "קונגו", club: "טרבזונספור", league: "Süper Lig" },
  { name: "סמואל מוטוסאמי", country: "קונגו", club: "סיוואספור", league: "Süper Lig" },
  { name: "ליונל אמפאסי", country: "קונגו", club: "רודז", league: "Ligue 2" },
  { name: "גדעון קאלולו", country: "קונגו", club: "לוריאן", league: "Ligue 2" },
  { name: "פפי אמאדו", country: "קונגו", club: "לסטר סיטי", league: "Premier League" },
  { name: "דילן בטובינסיקה", country: "קונגו", club: "סנט אטיין", league: "Ligue 1" },
  { name: "הנוק אינונגה באקה", country: "קונגו", club: "פ.א.ר רבאט", league: "Botola Pro 1" },
  { name: "שארל פיקל", country: "קונגו", club: "קרמונזה", league: "Serie B" },
  { name: "יאניק בולאסי", country: "קונגו", club: "קריסיומה", league: "Campeonato Brasileiro Série A" },
  { name: "ז'ורדן איקוקו", country: "קונגו", club: "פאפוס", league: "Cypriot First Division" },
  // אוזבקיסטן
  { name: "אלדור שומורודוב", country: "אוזבקיסטן", club: "רומא", league: "Serie A" },
  { name: "ג'לאלודין משאריפוב", country: "אוזבקיסטן", club: "אסתקלאל תהראן", league: "Persian Gulf Pro League" },
  { name: "אוסטון אורונוב", country: "אוזבקיסטן", club: "פרספוליס", league: "Persian Gulf Pro League" },
  { name: "איגור סרגייב", country: "אוזבקיסטן", club: "פאטום יונייטד", league: "Thai League 1" },
  { name: "עבאסבק פייזולאייב", country: "אוזבקיסטן", club: "צסק\"א מוסקבה", league: "Russian Premier League" },
  { name: "רוסטם אשורמטוב", country: "אוזבקיסטן", club: "רובין קאזאן", league: "Russian Premier League" },
  { name: "אודילז'ון חמרובקוב", country: "אוזבקיסטן", club: "נבבאהור נאמנגן", league: "Uzbekistan Super League" },
  { name: "חושמירוד עליקולוב", country: "אוזבקיסטן", club: "ריזספור", league: "Süper Lig" },
  { name: "פרחוד איסמעילוב", country: "אוזבקיסטן", club: "מטאלורג בקאבאד", league: "Uzbekistan Super League" },
  { name: "אומיד אומרוב", country: "אוזבקיסטן", club: "נסאף קארשי", league: "Uzbekistan Super League" },
  { name: "שאקחובוז אומארוב", country: "אוזבקיסטן", club: "אורדבאסי", league: "Kazakhstan Premier League" },
  { name: "האקם אלי קולוב", country: "אוזבקיסטן", club: "פאחטקור טשקנט", league: "Uzbekistan Super League" },
  { name: "אומיטקון עמנואלוף", country: "אוזבקיסטן", club: "בוניודקור", league: "Uzbekistan Super League" },
  { name: "זאפאר טושפולאטוב", country: "אוזבקיסטן", club: "נבבאהור נאמנגן", league: "Uzbekistan Super League" },
  { name: "עבדולה עבדולייב", country: "אוזבקיסטן", club: "חור פקאן", league: "UAE Pro League" },
  // קולומביה
  { name: "לואיס דיאס", country: "קולומביה", club: "ליברפול", league: "Premier League" },
  { name: "חאמס רודריגס", country: "קולומביה", club: "ראיו ואייקאנו", league: "La Liga" },
  { name: "ג'ון דוראן", country: "קולומביה", club: "אסטון וילה", league: "Premier League" },
  { name: "ריצ'רד ריוס", country: "קולומביה", club: "פלמיירס", league: "Campeonato Brasileiro Série A" },
  { name: "ג'פרסון לרמה", country: "קולומביה", club: "קריסטל פאלאס", league: "Premier League" },
  { name: "ג'ון אריאס", country: "קולומביה", club: "פלומיננסה", league: "Campeonato Brasileiro Série A" },
  { name: "דבינסון סאנצ'ס", country: "קולומביה", club: "גלאטסראיי", league: "Süper Lig" },
  { name: "ג'ון לוקומי", country: "קולומביה", club: "בולוניה", league: "Serie A" },
  { name: "דניאל מוניוס", country: "קולומביה", club: "קריסטל פאלאס", league: "Premier League" },
  { name: "קמילו ורגאס", country: "קולומביה", club: "אטלס", league: "Liga MX" },
  { name: "יוהאן מוחיקה", country: "קולומביה", club: "מיורקה", league: "La Liga" },
  { name: "רפאל בורה", country: "קולומביה", club: "אינטרנסיונל", league: "Campeonato Brasileiro Série A" },
  { name: "ג'ון קורדובה", country: "קולומביה", club: "קרסנודאר", league: "Russian Premier League" },
  { name: "קרלוס קואסטה", country: "קולומביה", club: "גנק", league: "Belgian Pro League" },
  { name: "יאסר אספרייה", country: "קולומביה", club: "ג'ירונה", league: "La Liga" }
];

const GROUP_L: Player[] = [
  // איטליה
  { name: "ג'אנלואיג'י דונארומה", country: "איטליה", club: "פריז סן ז'רמן", league: "Ligue 1" },
  { name: "אלסנדרו באסטוני", country: "איטליה", club: "אינטר מילאנו", league: "Serie A" },
  { name: "ניקולו בארלה", country: "איטליה", club: "אינטר מילאנו", league: "Serie A" },
  { name: "פדריקו קייזה", country: "איטליה", club: "ליברפול", league: "Premier League" },
  { name: "סנדרו טונאלי", country: "איטליה", club: "ניוקאסל יונייטד", league: "Premier League" },
  { name: "מתאו רטגי", country: "איטליה", club: "אטאלנטה", league: "Serie A" },
  { name: "ג'אקומו רספאדורי", country: "איטליה", club: "נאפולי", league: "Serie A" },
  { name: "דוידה פראטזי", country: "איטליה", club: "אינטר מילאנו", league: "Serie A" },
  { name: "פדריקו דימרקו", country: "איטליה", club: "אינטר מילאנו", league: "Serie A" },
  { name: "ג'ובאני די לורנצו", country: "איטליה", club: "נאפולי", league: "Serie A" },
  { name: "ריקרדו קלאפיורי", country: "איטליה", club: "ארסנל", league: "Premier League" },
  { name: "לורנצו פלגריני", country: "איטליה", club: "רומא", league: "Serie A" },
  { name: "גוליילמו ויקאריו", country: "איטליה", club: "טוטנהאם הוטספור", league: "Premier League" },
  { name: "מתיה זקאני", country: "איטליה", club: "לאציו", league: "Serie A" },
  { name: "מנואל לוקאטלי", country: "איטליה", club: "יובנטוס", league: "Serie A" },
  // ניגריה
  { name: "ויקטור אוסימן", country: "ניגריה", club: "גלאטסראיי", league: "Süper Lig" },
  { name: "אדמולה לוקמן", country: "ניגריה", club: "אטאלנטה", league: "Serie A" },
  { name: "ויקטור בוניפאס", country: "ניגריה", club: "באייר לברקוזן", league: "Bundesliga" },
  { name: "סמואל צ'וקוואזה", country: "ניגריה", club: "מילאן", league: "Serie A" },
  { name: "אלכס איוובי", country: "ניגריה", club: "פולהאם", league: "Premier League" },
  { name: "וילפרד אנדידי", country: "ניגריה", club: "לסטר סיטי", league: "Premier League" },
  { name: "קלווין באסי", country: "ניגריה", club: "פולהאם", league: "Premier League" },
  { name: "סמי אג'אי", country: "ניגריה", club: "ווסט ברומיץ' אלביון", league: "Championship" },
  { name: "ויליאם טרוסט-אקונג", country: "ניגריה", club: "אל חולוד", league: "Saudi Pro League" },
  { name: "אולה איינה", country: "ניגריה", club: "נוטינגהאם פורסט", league: "Premier League" },
  { name: "סטנלי נוואבלי", country: "ניגריה", club: "צ'יפה יונייטד", league: "South African Premier Division" },
  { name: "טאיבו אווניאי", country: "ניגריה", club: "נוטינגהאם פורסט", league: "Premier League" },
  { name: "זאידו סאנוסי", country: "ניגריה", club: "פורטו", league: "Primeira Liga" },
  { name: "רפאל אונידיקה", country: "ניגריה", club: "קלאב ברוז'", league: "Belgian Pro League" },
  { name: "סיריל דסרס", country: "ניגריה", club: "ריינג'רס", league: "Scottish Premiership" },
  // קרואטיה
  { name: "לוקה מודריץ'", country: "קרואטיה", club: "ריאל מדריד", league: "La Liga" },
  { name: "יושקו גברדיול", country: "קרואטיה", club: "מנצ'סטר סיטי", league: "Premier League" },
  { name: "מתאו קובאצ'יץ'", country: "קרואטיה", club: "מנצ'סטר סיטי", league: "Premier League" },
  { name: "מרסלו ברוזוביץ'", country: "קרואטיה", club: "אל-נאסר", league: "Saudi Pro League" },
  { name: "דומיניק ליבאקוביץ'", country: "קרואטיה", club: "פנרבחצ'ה", league: "Süper Lig" },
  { name: "אנדריי קרמאריץ'", country: "קרואטיה", club: "הופנהיים", league: "Bundesliga" },
  { name: "איבן פרישיץ'", country: "קרואטיה", club: "פ.ס.וו איינדהובן", league: "Eredivisie" },
  { name: "ברונו פטקוביץ'", country: "קרואטיה", club: "דינמו זאגרב", league: "Prva HNL" },
  { name: "מריו פשאליץ'", country: "קרואטיה", club: "אטאלנטה", league: "Serie A" },
  { name: "יוסיפ שוטאלו", country: "קרואטיה", club: "אייאקס", league: "Eredivisie" },
  { name: "בורנה סוסה", country: "קרואטיה", club: "טורינו", league: "Serie A" },
  { name: "לוברן מאייר", country: "קרואטיה", club: "וולפסבורג", league: "Bundesliga" },
  { name: "לוקה סוצ'יץ'", country: "קרואטיה", club: "ריאל סוסיאדד", league: "La Liga" },
  { name: "מרטין בטורינה", country: "קרואטיה", club: "דינמו זאגרב", league: "Prva HNL" },
  { name: "דומיניק קוטארסקי", country: "קרואטיה", club: "פאוק סלוניקי", league: "Super League Greece" },
  // אנגליה
  { name: "הארי קיין", country: "אנגליה", club: "באיירן מינכן", league: "Bundesliga" },
  { name: "ג'וד בלינגהאם", country: "אנגליה", club: "ריאל מדריד", league: "La Liga" },
  { name: "פיל פודן", country: "אנגליה", club: "מנצ'סטר סיטי", league: "Premier League" },
  { name: "דקלאן רייס", country: "אנגליה", club: "ארסנל", league: "Premier League" },
  { name: "בוקאיו סאקה", country: "אנגליה", club: "ארסנל", league: "Premier League" },
  { name: "קול פאלמר", country: "אנגליה", club: "צ'לסי", league: "Premier League" },
  { name: "ג'ורדן פיקפורד", country: "אנגליה", club: "אברטון", league: "Premier League" },
  { name: "ג'ון סטונס", country: "אנגליה", club: "מנצ'סטר סיטי", league: "Premier League" },
  { name: "מארק גהי", country: "אנגליה", club: "קריסטל פאלאס", league: "Premier League" },
  { name: "טרנט אלכסנדר-ארנולד", country: "אנגליה", club: "ליברפול", league: "Premier League" },
  { name: "קייל ווקר", country: "אנגליה", club: "מנצ'סטר סיטי", league: "Premier League" },
  { name: "ג'ק גריליש", country: "אנגליה", club: "מנצ'סטר סיטי", league: "Premier League" },
  { name: "אולי ווטקינס", country: "אנגליה", club: "אסטון וילה", league: "Premier League" },
  { name: "קובי מאיינו", country: "אנגליה", club: "מנצ'סטר יונייטד", league: "Premier League" },
  { name: "אנתוני גורדון", country: "אנגליה", club: "ניוקאסל יונייטד", league: "Premier League" }
];

export const PLAYERS_DATA: Player[] = [
  ...GROUP_A,
  ...GROUP_B,
  ...GROUP_C,
  ...GROUP_D,
  ...GROUP_E,
  ...GROUP_F,
  ...GROUP_G,
  ...GROUP_H,
  ...GROUP_I,
  ...GROUP_J,
  ...GROUP_K,
  ...GROUP_L
];


export const getPlayersByCountry = (country: string) => PLAYERS_DATA.filter(p => p.country === country);
// רשימת שמות עבור ה-Autocomplete
export const TOP_PLAYERS_NAMES = PLAYERS_DATA.map(p => p.name);

// פונקציית עזר לשליפת מידע מלא על שחקן לפי שמו
export const getPlayerInfo = (name: string) => PLAYERS_DATA.find(p => p.name === name);
// --- להוסיף בסוף הקובץ app/utils/players.ts ---

// מחלץ רשימה ייחודית וממוינת של כל המועדונים
export const TOP_CLUBS_NAMES = Array.from(
  new Set(PLAYERS_DATA.map(p => p.club))
).filter(Boolean).sort();

// מחלץ רשימה ייחודית וממוינת של כל הליגות
export const TOP_LEAGUES_NAMES = Array.from(
  new Set(PLAYERS_DATA.map(p => p.league))
).filter(Boolean).sort();

// פונקציית עזר למציאת שחקנים לפי מועדון או ליגה (ישמש אותנו לדשבורד בהמשך)
export const getPlayersByClub = (club: string) => PLAYERS_DATA.filter(p => p.club === club);
export const getPlayersByLeague = (league: string) => PLAYERS_DATA.filter(p => p.league === league);